const actionTypes = {
  FETCH_USERS_LIST_ASYNC: 'FETCH_USERS_LIST_ASYNC',
  FETCH_USERS_LIST_OK: 'FETCH_USERS_LIST_OK',
  FETCH_USER_DETAIL_ASYNC: 'FETCH_USER_DETAIL_ASYNC',
  FETCH_USER_DETAIL_TWEETS_OK: 'FETCH_USER_DETAIL_TWEETS_OK',
  FETCH_USER_DETAIL_USER_OK: 'FETCH_USER_DETAIL_USER_OK',
  ON_CLICK_SEARCH_BUTTON_ASYNC: 'ON_CLICK_SEARCH_BUTTON_ASYNC',
  ON_CLICK_USER_ASYNC: 'ON_CLICK_USER_ASYNC',
}

export default actionTypes